#!/bin/bash

source /c/GitNova/cmds/utils/utils

__version__="2.3.5"

## DEFAULT HOST & PORT
HOST='127.0.0.1'
PORT='8080' 


banner_g() {
echo "${CY} <<--NoVa-->>" ${__version__}
}


about() {
    echo "${GG}About this script:"
    echo "${GG}Version: ${__version__}"
    echo "${GG}This script provides various utility functions for repo management."
    echo "${GG}This repo was created by gitty-thesis on github"
    echo
    echo "${CY}This is a list this of available commands"
}

exit_script() {
    echo "${GG}Exiting script..."
    clear
    exit 0
}

# Main Menu
main_menu() {
    while true; do
        clear
        banner_g
        echo
        echo -e "${RE}[${WHITE}1${RE}]${OG} Configuration and Setup --> ${GG} n-config"
        echo -e "${RE}[${WHITE}2${RE}]${OG} Branch Management --> ${GG} n-branch"
        echo -e "${RE}[${WHITE}3${RE}]${OG} Staging and Stash --> ${GG} n-stage"
        echo -e "${RE}[${WHITE}4${RE}]${OG} Commit Changes --> ${GG} n-commit"
        echo -e "${RE}[${WHITE}5${RE}]${OG} Undoing Changes --> ${GG} n-undo"
        echo -e "${RE}[${WHITE}6${RE}]${OG} Remote Repositories --> ${GG} n-remote"
        echo -e "${RE}[${WHITE}7${RE}]${OG} Logs and History --> ${GG} n-logs"
        echo -e "${RE}[${WHITE}8${RE}]${OG} Working with Submodules --> ${GG} n-subm"
        echo -e "${RE}[${WHITE}9${RE}]${OG} Advanced Commands --> ${GG} n-adv"
        echo -e "${RE}[${WHITE}10${RE}]${OG} Clean Up  --> ${GG} n-clean"
        echo -e "${RE}[${WHITE}11${RE}]${OG} Tagging --> ${GG} n-tag"
        echo -e "${RE}[${WHITE}99${RE}]${OG} About  --> ${GG} about"
        echo -e "${RE}[${WHITE}0${RE}]${OG} Exit"
        echo
        read -p "${RE}[${WHITE}-${RE}]${GG} Select an option: ${BB}" selected

        case $selected in
            1) source /c/GitNova/cmds/n-config ;;
            2) source /c/GItNova/cmds/n-branch ;;
            3) source /c/GitNova/cmds/n-stage ;;
            4) source /c/GitNova/cmds/n-commit ;;
            5) source /c/GitNova/cmds/n-undo ;;
            6) source /c/GitNova/cmds/n-remote ;;
            7) source /c/GitNova/cmds/n-logs ;;
            8) source /c/GitNova/cmds/n-subm ;;
            9) source /c/GitNova/cmds/n-adv ;;
            10) source /c/GitNova/cmds/n-clean ;;
            11) source /c/GitNova/cmds/n-tag ;;
            99) about ;;
            0) exit_script ;;
            *) echo "${RE}Invalid option! Please try again." ;;
        esac

        read -p "${GG}Press [Enter] to continue..." dummy
    done
}

# Run the menu
check_git_repo
main_menu