#!/bin/bash

source /c/GitNova/cmds/utils/utils

__version__="2.3.5"

## DEFAULT HOST & PORT
HOST='127.0.0.1'
PORT='8080' 


banner_g() {
echo "${CYAN} <<--NoVa-->>" ${__version__}
}


about() {
    echo "${GREEN}About this script:"
    echo "${GREEN}Version: ${__version__}"
    echo "${GREEN}This script provides various utility functions for repo management."
    echo "${GREEN}This repo was created by gitty-thesis on github"
    echo
    echo "${CYAN}This is a list this of available commands"
}

exit_script() {
    echo "${GREEN}Exiting script..."
    clear
    exit 0
}

# Main Menu
main_menu() {
    while true; do
        clear
        banner_g
        echo
        echo -e "${RED}[${WHITE}1${RED}]${ORANGE} Configuration and Setup --> ${GREEN} n-config"
        echo -e "${RED}[${WHITE}2${RED}]${ORANGE} Branch Management --> ${GREEN} n-branch"
        echo -e "${RED}[${WHITE}3${RED}]${ORANGE} Staging and Stash --> ${GREEN} n-stage"
        echo -e "${RED}[${WHITE}4${RED}]${ORANGE} Commit Changes --> ${GREEN} n-commit"
        echo -e "${RED}[${WHITE}5${RED}]${ORANGE} Undoing Changes --> ${GREEN} n-undo"
        echo -e "${RED}[${WHITE}6${RED}]${ORANGE} Remote Repositories --> ${GREEN} n-remote"
        echo -e "${RED}[${WHITE}7${RED}]${ORANGE} Logs and History --> ${GREEN} n-logs"
        echo -e "${RED}[${WHITE}8${RED}]${ORANGE} Working with Submodules --> ${GREEN} n-subm"
        echo -e "${RED}[${WHITE}9${RED}]${ORANGE} Advanced Commands --> ${GREEN} n-adv"
        echo -e "${RED}[${WHITE}10${RED}]${ORANGE} Clean Up  --> ${GREEN} n-clean"
        echo -e "${RED}[${WHITE}11${RED}]${ORANGE} Tagging --> ${GREEN} n-tag"
        echo -e "${RED}[${WHITE}99${RED}]${ORANGE} About  --> ${GREEN} about"
        echo -e "${RED}[${WHITE}0${RED}]${ORANGE} Exit"
        echo
        read -p "${RED}[${WHITE}-${RED}]${GREEN} Select an option: ${BLUE}" selected

        case $selected in
            1) source /c/GitNova/cmds/n-config ;;
            2) source /c/GItNova/cmds/n-branch ;;
            3) source /c/GitNova/cmds/n-stage ;;
            4) source /c/GitNova/cmds/n-commit ;;
            5) source /c/GitNova/cmds/n-undo ;;
            6) source /c/GitNova/cmds/n-remote ;;
            7) source /c/GitNova/cmds/n-logs ;;
            8) source /c/GitNova/cmds/n-subm ;;
            9) source /c/GitNova/cmds/n-adv ;;
            10) source /c/GitNova/cmds/n-clean ;;
            11) source /c/GitNova/cmds/n-tag ;;
            99) about ;;
            0) exit_script ;;
            *) echo "${RED}Invalid option! Please try again." ;;
        esac

        read -p "${GREEN}Press [Enter] to continue..." dummy
    done
}

# Run the menu
check_git_repo
main_menu