#!/bin/bash

source /c/GitNova/cmds/utils/utils


# Configuration and Setup Functions
configuration_setup() {
    while true; do
        clear
        echo -e "${RE}Configuration and Setup Options:${RT}"
        echo -e "${RE}[${WH}1${RE}]${OG} Set user name ${GG}git config --global user.name username"
        echo -e "${RE}[${WH}2${RE}]${OG} Set user email ${GG}git config --global user.email useremail"
        echo -e "${RE}[${WH}3${RE}]${OG} View configuration ${GG}git config --list"
        echo -e "${RE}[${WH}4${RE}]${OG} Initialize repository ${GG}git init"
        echo -e "${RE}[${WH}5${RE}]${OG} Set default branch name ${GG}git config --global init.defaultBranch main"
        echo -e "${RE}[${WH}6${RE}]${OG} Set default text editor ${GG}git config --global core.editor vim"
        echo -e "${RE}[${WH}7${RE}]${OG} Set GPG signing key ${GG}git config --global user.signingKey <GPG_KEY_ID>"
        echo -e "${RE}[${WH}8${RE}]${OG} Unset configuration ${GG}git config --global --unset <key>"
        echo -e "${RE}[${WH}0${RE}]${OG} Back to main menu"
        echo
        read -p "${RE}[${WH}-${RE}]${GG} Select an option: ${BB}" selected

        case $selected in
            1) set_user_name ;;
            2) set_user_email ;;
            3) view_config ;;
            4) initialise ;;
            5) set_default_branch ;;
            6) set_default_editor ;;
            7) set_gpg_signing_key ;;
            8) unset_config ;;
            0) clear; break ;;
            *)
                echo "${RE}Invalid option! Please try again."
                ;;
        esac

        read -p "${GG}Press [Enter] to continue..." dummy
    done
}

set_user_name() {
    read -p "${GG}Enter your name: ${BB}" name
    if [[ -z "$name" ]]; then
        echo -e "${RE}Error: Name cannot be empty.${RT}"
        return
    fi
    git config --global user.name "$name" || echo -e "${RE}Error: Failed to set user name.${RT}"
    echo -e "${GG}User name set to $name${RT}"
}

set_user_email() {
    read -p "${GG}Enter your email: ${BB}" email
    if [[ ! "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
        echo -e "${RE}Error: Invalid email format.${RT}"
        return
    fi
    git config --global user.email "$email" || echo -e "${RE}Error: Failed to set user email.${RT}"
    echo -e "${GG}User email set to $email${RT}"
}

view_config() {
    echo -e "${GG}Git Configuration:${RT}"
    git config --global --list
}

initialise() {
    read -p "${GG}Enter the directory to initialize (leave blank for current directory): ${BB}" dir
    if [[ -z "$dir" ]]; then
        git init || echo -e "${RE}Error: Failed to initialize repository.${RT}"
    else
        git init "$dir" || echo -e "${RE}Error: Failed to initialize repository in '$dir'.${RT}"
    fi
    echo -e "${GG}Repository initialized.${RT}"
}

set_default_branch() {
    read -p "${GG}Enter the default branch name (e.g., main): ${BB}" branch
    if [[ -z "$branch" ]]; then
        echo -e "${RE}Error: Branch name cannot be empty.${RT}"
        return
    fi
    git config --global init.defaultBranch "$branch" || echo -e "${RE}Error: Failed to set default branch.${RT}"
    echo -e "${GG}Default branch set to '$branch'.${RT}"
}

set_default_editor() {
    read -p "${GG}Enter the default text editor (e.g., vim, nano, code): ${BB}" editor
    if [[ -z "$editor" ]]; then
        echo -e "${RE}Error: Editor name cannot be empty.${RT}"
        return
    fi
    git config --global core.editor "$editor" || echo -e "${RE}Error: Failed to set default editor.${RT}"
    echo -e "${GG}Default editor set to '$editor'.${RT}"
}

set_gpg_signing_key() {
    read -p "${GG}Enter your GPG signing key ID: ${BB}" gpg_key
    if [[ -z "$gpg_key" ]]; then
        echo -e "${RE}Error: GPG key ID cannot be empty.${RT}"
        return
    fi
    git config --global user.signingKey "$gpg_key" || echo -e "${RE}Error: Failed to set GPG signing key.${RT}"
    echo -e "${GG}GPG signing key set to '$gpg_key'.${RT}"
}

unset_config() {
    echo -e "${GG}Select the configuration to unset:${RT}"
    echo -e "${RE}[${WH}1${RE}]${OG} Unset user name ${GG}git config --global --unset user.name"
    echo -e "${RE}[${WH}2${RE}]${OG} Unset user email ${GG}git config --global --unset user.email"
    echo -e "${RE}[${WH}3${RE}]${OG} Unset default branch ${GG}git config --global --unset init.defaultBranch"
    echo -e "${RE}[${WH}4${RE}]${OG} Unset default editor ${GG}git config --global --unset core.editor"
    echo -e "${RE}[${WH}5${RE}]${OG} Unset GPG signing key ${GG}git config --global --unset user.signingKey"
    echo -e "${RE}[${WH}0${RE}]${OG} Back to main menu"
    echo
    read -p "${RE}[${WH}-${RE}]${GG} Select an option: ${BB}" unset_option

    case $unset_option in
        1) git config --global --unset user.name && echo -e "${GG}User name unset.${RT}" ;;
        2) git config --global --unset user.email && echo -e "${GG}User email unset.${RT}" ;;
        3) git config --global --unset init.defaultBranch && echo -e "${GG}Default branch unset.${RT}" ;;
        4) git config --global --unset core.editor && echo -e "${GG}Default editor unset.${RT}" ;;
        5) git config --global --unset user.signingKey && echo -e "${GG}GPG signing key unset.${RT}" ;;
        0) return ;;
        *) echo -e "${RE}Invalid option! Please try again.${RT}" ;;
    esac
}

configuration_setup