#!/bin/bash

source /c/GitNova/cmds/utils/utils

# Logs and History Menu
logs_history_menu() {
    while true; do
        clear
        echo -e "${CY}Logs and History Commands Options:${RT}"
        echo -e "${RE}[${WH}1${RE}]${OG} View commit history ${GG}git log"
        echo -e "${RE}[${WH}2${RE}]${OG} View one-line commit history ${GG}git log --oneline"
        echo -e "${RE}[${WH}3${RE}]${OG} View commit history with graph ${GG}git log --oneline --graph"
        echo -e "${RE}[${WH}4${RE}]${OG} View the last N commits ${GG}git log -n N"
        echo -e "${RE}[${WH}5${RE}]${OG} View a specific file's commit history ${GG}git log -- file_name"
        echo -e "${RE}[${WH}0${RE}]${OG} Back to main menu"
        echo
        read -p "${RE}[${WH}-${RE}]${GG} Select an option: ${BB}" selected

        case $selected in
            1) view_commit_history ;;
            2) view_oneline_commit_history ;;
            3) view_commit_graph ;;
            4) view_last_n_commits ;;
            5) view_file_commit_history ;;
            0) clear; break ;;  # Exit the loop and return to the main menu
            *) echo "${RE}Invalid option! Please try again.${RT}" ;;
        esac

        read -p "${GG}Press [Enter] to return to the menu...${RT}"
    done
}

# Functions for each option
view_commit_history() {
    echo "${GG}Commit history:${RT}"
    git log
}

view_oneline_commit_history() {
    echo "${GG}One-line commit history:${RT}"
    git log --oneline
}

view_commit_graph() {
    echo "${GG}Commit history with graph:${RT}"
    git log --oneline --graph
}

view_last_n_commits() {
    read -p "${GG}Enter the number of commits to view: ${BB}" n
    echo "${GG}Last $n commits:${RT}"
    git log -n "$n"
}

view_file_commit_history() {
    read -p "${GG}Enter the file name: ${BB}" file_name
    echo "${GG}Commit history for '$file_name':${RT}"
    git log -- "$file_name"
}

check_git_repo
logs_history_menu
